# Generated by Django 4.1.2 on 2022-10-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('MessageContent', models.TextField()),
                ('publicaitonDate', models.DateTimeField(verbose_name='PublicationDate')),
                ('publishedBy', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryTitle', models.CharField(max_length=100)),
                ('publicationDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='discussionBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardMessage', models.TextField()),
                ('publicaitonDate', models.DateTimeField(verbose_name='PublicationDate')),
                ('publishedBy', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FileAndDocumentBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileCategory', models.CharField(max_length=100)),
                ('fileContent', models.FileField(upload_to='')),
                ('publicaitonDate', models.DateTimeField(verbose_name='PublicationDate')),
                ('publishedBy', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='systemAdministrators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=100)),
                ('jobPosition', models.CharField(max_length=100)),
                ('profilePicture', models.FileField(upload_to='')),
                ('userName', models.CharField(max_length=100)),
                ('PassWord', models.CharField(max_length=100)),
                ('publicaitonDate', models.DateTimeField(verbose_name='PublicationDate')),
                ('publishedBy', models.CharField(max_length=100)),
            ],
        ),
    ]
